// Package gateway provides the HTTP/REST reverse proxy for the FND gRPC service.
// It uses gRPC-Gateway to expose REST endpoints and serves Swagger UI.
package gateway

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"log/slog"
	"net/http"
	"strings"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/protobuf/encoding/protojson"

	fndv1 "go-transfer-agent/common/gen/fnd/v1"
)

//go:embed swagger-ui/*
var swaggerUIFS embed.FS

//go:embed fnd.swagger.json
var swaggerJSON []byte

// NewHTTPServer creates an HTTP server that:
// 1. Proxies REST requests to the gRPC service via gRPC-Gateway
// 2. Serves Swagger UI at /swagger/
// 3. Serves the OpenAPI spec at /swagger/fnd.swagger.json
func NewHTTPServer(ctx context.Context, grpcAddr string, log *slog.Logger) (http.Handler, error) {
	mux := http.NewServeMux()

	// ─── gRPC-Gateway reverse proxy ───
	gwMux := runtime.NewServeMux(
		runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{
			MarshalOptions: protojson.MarshalOptions{
				UseProtoNames:   false, // Will use JSON names generated by python script (PascalCase)
				EmitUnpopulated: true,  // Emits default values (e.g. 0, "", false) instead of dropping them
			},
			UnmarshalOptions: protojson.UnmarshalOptions{
				DiscardUnknown: true,
			},
		}),
	)
	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}

	// ─── Register all FND module gRPC-Gateway handlers ───
	registrations := []struct {
		name string
		fn   func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error
	}{
		{"FNDService (FNDM001)", fndv1.RegisterFNDServiceHandlerFromEndpoint},
		{"FNDM002Service", fndv1.RegisterFNDM002ServiceHandlerFromEndpoint},
		{"FNDM003Service", fndv1.RegisterFNDM003ServiceHandlerFromEndpoint},
		{"FNDM004Service", fndv1.RegisterFNDM004ServiceHandlerFromEndpoint},
		{"FNDM005Service", fndv1.RegisterFNDM005ServiceHandlerFromEndpoint},
		{"FNDM006Service", fndv1.RegisterFNDM006ServiceHandlerFromEndpoint},
		{"FNDM007Service", fndv1.RegisterFNDM007ServiceHandlerFromEndpoint},
		{"FNDM008Service", fndv1.RegisterFNDM008ServiceHandlerFromEndpoint},
		{"FNDM009Service", fndv1.RegisterFNDM009ServiceHandlerFromEndpoint},
		{"FNDM010Service", fndv1.RegisterFNDM010ServiceHandlerFromEndpoint},
		{"FNDM011Service", fndv1.RegisterFNDM011ServiceHandlerFromEndpoint},
		{"FNDM012Service", fndv1.RegisterFNDM012ServiceHandlerFromEndpoint},
		{"FNDM013Service", fndv1.RegisterFNDM013ServiceHandlerFromEndpoint},
	}

	for _, r := range registrations {
		if err := r.fn(ctx, gwMux, grpcAddr, opts); err != nil {
			return nil, fmt.Errorf("failed to register gateway for %s: %w", r.name, err)
		}
	}

	// ─── Swagger UI ───
	subFS, err := fs.Sub(swaggerUIFS, "swagger-ui")
	if err != nil {
		return nil, fmt.Errorf("failed to mount swagger-ui: %w", err)
	}
	swaggerFileServer := http.FileServer(http.FS(subFS))

	// Serve OpenAPI spec
	mux.HandleFunc("/swagger/fnd.swagger.json", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(swaggerJSON)
	})

	// Serve Swagger UI static files
	mux.Handle("/swagger/", http.StripPrefix("/swagger/", swaggerFileServer))

	// Serve root redirect to swagger
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" {
			http.Redirect(w, r, "/swagger/", http.StatusTemporaryRedirect)
			return
		}
		// Forward non-swagger, non-root requests to gRPC-Gateway
		gwMux.ServeHTTP(w, r)
	})

	// Forward API routes to gRPC-Gateway
	mux.Handle("/TAapi/", gwMux)
	mux.Handle("/BaseFund/", gwMux)

	// ─── CORS middleware (for Bruno/Postman) ───
	handler := corsMiddleware(mux)

	log.Info("HTTP gateway configured",
		slog.String("grpc_target", grpcAddr),
		slog.String("swagger_ui", "/swagger/"),
		slog.Int("services", len(registrations)),
	)

	return handler, nil
}

func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Requested-With")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// GenerateSwaggerUIIndex generates a minimal index.html for Swagger UI
// that points to our OpenAPI spec.
func GenerateSwaggerUIIndex() string {
	return strings.TrimSpace(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>FND Service - Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
  <style>body { margin: 0; } .topbar { display: none; }</style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url: "/swagger/fnd.swagger.json",
      dom_id: '#swagger-ui',
      presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
      layout: "BaseLayout",
      deepLinking: true,
      tryItOutEnabled: true,
    });
  </script>
</body>
</html>
`)
}

// PrettyJSON re-marshals the embedded swagger spec with indentation (for debugging).
func PrettyJSON() ([]byte, error) {
	var v interface{}
	if err := json.Unmarshal(swaggerJSON, &v); err != nil {
		return nil, err
	}
	return json.MarshalIndent(v, "", "  ")
}
