package fndm013

import (
	"context"
	"log/slog"
	"time"

	fndv1 "go-transfer-agent/common/gen/fnd/v1"
	"go-transfer-agent/services/fnd/fndm013/db"
	"go-transfer-agent/services/fnd/shared"

	"go-transfer-agent/common/platform/model"
	"gorm.io/gorm"
)

// Service holds the FNDM013 business logic.
type Service struct {
	db  *gorm.DB
	log *slog.Logger
}

// NewService creates a new FNDM013 service overriding the in-memory mock.
func NewService(database *gorm.DB, logger *slog.Logger) *Service {
	return &Service{
		db:  database,
		log: logger.With(slog.String("module", "fndm013-service")),
	}
}

// TAFNDTMFundFeeRdm retrieves Master and Detail structures from PostgreSQL via GORM.
func (s *Service) TAFNDTMFundFeeRdm(ctx context.Context, req *fndv1.TAFNDTMFundFeeRdmRequest) (*fndv1.TAFNDTMFundFeeRdmResponse, error) {
	sysCoID := req.GetSysCoId()
	prtFundCode := req.GetPrtFundCode()
	rdmCalcBegDate := req.GetRdmCalcBegDate()

	resp := &fndv1.TAFNDTMFundFeeRdmResponse{
		ResultList:     make([]*fndv1.TMFundFeeRdmMasterDTO, 0),
		FundFeeDtlList: make([]*fndv1.TMFundFeeRdmDtlListDTO, 0),
	}

	// 1. Query Master
	masterQuery := s.db.WithContext(ctx).Model(&db.DTAFNDTMFundFeeRdm{}).Where("SysCoID = ?", sysCoID)
	if prtFundCode != "" {
		masterQuery = masterQuery.Where("PrtFundCode = ?", prtFundCode)
	}
	if rdmCalcBegDate != "" {
		masterQuery = masterQuery.Where("RdmCalcBegDate = ?", rdmCalcBegDate)
	}

	var masters []db.DTAFNDTMFundFeeRdm
	if err := masterQuery.Find(&masters).Error; err != nil {
		s.log.Error("Failed to query DTAFNDTMFundFeeRdm", slog.Any("error", err))
		return nil, err
	}

	for _, m := range masters {
		dto := &fndv1.TMFundFeeRdmMasterDTO{
			SysCoId:        m.SysCoID,
			SysCoIdNm:      shared.GetSysCoName(m.SysCoID),
			PrtFundCode:    m.PrtFundCode,
			PrtFundCodeNm:  shared.GetDFundName(m.PrtFundCode),
			RdmCalcBegDate: m.RdmCalcBegDate.Format(time.RFC3339),
		}
		resp.ResultList = append(resp.ResultList, dto)
	}

	// 2. Query Detail
	dtlQuery := s.db.WithContext(ctx).Model(&db.DTAFNDTMFundFeeRdmDtl{}).Where("SysCoID = ?", sysCoID)
	if prtFundCode != "" {
		dtlQuery = dtlQuery.Where("PrtFundCode = ?", prtFundCode)
	}
	if rdmCalcBegDate != "" {
		dtlQuery = dtlQuery.Where("RdmCalcBegDate = ?", rdmCalcBegDate)
	}

	var details []db.DTAFNDTMFundFeeRdmDtl
	if err := dtlQuery.Find(&details).Error; err != nil {
		s.log.Error("Failed to query DTAFNDTMFundFeeRdmDtl", slog.Any("error", err))
		return nil, err
	}

	for _, d := range details {
		dto := &fndv1.TMFundFeeRdmDtlListDTO{
			SysCoId:        d.SysCoID,
			PrtFundCode:    d.PrtFundCode,
			RdmCalcBegDate: d.RdmCalcBegDate.Format(time.RFC3339),
			RdmCalcEndDate: d.RdmCalcEndDate.Format(time.RFC3339),
			FeeRate:        d.FeeRate.InexactFloat64(),
		}
		resp.FundFeeDtlList = append(resp.FundFeeDtlList, dto)
	}

	return resp, nil
}

// SaveTAFNDTMFundFeeRdm creates a new record in the _Edit table — POST endpoint.
func (s *Service) SaveTAFNDTMFundFeeRdm(ctx context.Context, req *fndv1.TAFNDTMFundFeeRdmRequest) (*fndv1.SaveResponse, error) {
	s.log.Info("SaveTAFNDTMFundFeeRdm called")

	record := db.DTAFNDTMFundFeeRdm{}
	// Auth Context & 4-Eyes Principle
	record.MakerID = shared.GetUsernameFromCtx(ctx)
	record.Status = models.StatusPendingApproval

	record.SysCoID = req.GetSysCoId()
	record.PrtFundCode = req.GetPrtFundCode()
	// DataID is auto-generated by the DB (gen_random_uuid)

	if err := s.db.WithContext(ctx).Create(&record).Error; err != nil {
		s.log.Error("SaveTAFNDTMFundFeeRdm failed", slog.Any("error", err))
		return &fndv1.SaveResponse{
			Success: false, Message: err.Error(), ReturnCode: "DB_ERROR",
		}, nil
	}

	return &fndv1.SaveResponse{
		Success: true, Message: "Record created successfully", ReturnCode: "0000",
	}, nil
}

// UpdateTAFNDTMFundFeeRdm updates an existing record in the _Edit table — PUT endpoint.
func (s *Service) UpdateTAFNDTMFundFeeRdm(ctx context.Context, req *fndv1.TAFNDTMFundFeeRdmRequest) (*fndv1.SaveResponse, error) {
	s.log.Info("UpdateTAFNDTMFundFeeRdm called")

	record := db.DTAFNDTMFundFeeRdm{}
	record.SysCoID = req.GetSysCoId()
	record.PrtFundCode = req.GetPrtFundCode()

	result := s.db.WithContext(ctx).Model(&db.DTAFNDTMFundFeeRdm{}).
		Where(`"DataID" = ?`, req.GetSysCoId()).Updates(&record)
	if result.Error != nil {
		s.log.Error("UpdateTAFNDTMFundFeeRdm failed", slog.Any("error", result.Error))
		return &fndv1.SaveResponse{
			Success: false, Message: result.Error.Error(), ReturnCode: "DB_ERROR",
		}, nil
	}
	if result.RowsAffected == 0 {
		return &fndv1.SaveResponse{
			Success: false, Message: "No record found to update", ReturnCode: "NOT_FOUND",
		}, nil
	}

	return &fndv1.SaveResponse{
		Success: true, Message: "Record updated successfully", ReturnCode: "0000",
	}, nil
}

// DeleteTAFNDTMFundFeeRdm removes a record from the _Edit table by DataID — DELETE endpoint.
func (s *Service) DeleteTAFNDTMFundFeeRdm(ctx context.Context, req *fndv1.DeleteRequest) (*fndv1.SaveResponse, error) {
	s.log.Info("DeleteTAFNDTMFundFeeRdm called",
		slog.String("data_id", req.GetDataId()),
		slog.String("data_flag", req.GetDataFlag()),
	)

	result := s.db.WithContext(ctx).
		Where(`"DataID" = ?`, req.GetDataId()).
		Delete(&db.DTAFNDTMFundFeeRdm{})
	if result.Error != nil {
		s.log.Error("DeleteTAFNDTMFundFeeRdm failed", slog.Any("error", result.Error))
		return &fndv1.SaveResponse{
			Success: false, Message: result.Error.Error(), ReturnCode: "DB_ERROR",
		}, nil
	}
	if result.RowsAffected == 0 {
		return &fndv1.SaveResponse{
			Success: false, Message: "No record found with the given DataID", ReturnCode: "NOT_FOUND",
		}, nil
	}

	return &fndv1.SaveResponse{
		Success: true, Message: "Record deleted successfully", ReturnCode: "0000",
	}, nil
}

// GetDataByDataID retrieves full data by DataID.
func (s *Service) GetDataByDataID(ctx context.Context, req *fndv1.GetDataRequest) (*fndv1.TAFNDTMFundFeeRdmRequest, error) {
	return &fndv1.TAFNDTMFundFeeRdmRequest{}, nil
}

// ApproveTAFNDTMFundFeeRdm approves or rejects a pending record for the 4-Eyes Principle.
func (s *Service) ApproveTAFNDTMFundFeeRdm(ctx context.Context, req *fndv1.ApproveTAFNDTMFundFeeRdmRequest) (*fndv1.SaveResponse, error) {
	s.log.Info("ApproveTAFNDTMFundFeeRdm called", slog.String("data_id", req.GetDataId()))

	var record db.DTAFNDTMFundFeeRdm
	result := s.db.WithContext(ctx).Where("\"DataID\" = ?", req.GetDataId()).First(&record)
	
	if result.Error != nil {
		if result.Error == gorm.ErrRecordNotFound {
			return &fndv1.SaveResponse{Success: false, Message: "Record not found", ReturnCode: "NOT_FOUND"}, nil
		}
		s.log.Error("ApproveTAFNDTMFundFeeRdm DB error", slog.Any("error", result.Error))
		return &fndv1.SaveResponse{Success: false, Message: result.Error.Error(), ReturnCode: "DB_ERROR"}, nil
	}

	// Only allow approval if status is PENDING_APPROVAL
	if record.Status != models.StatusPendingApproval {
		return &fndv1.SaveResponse{Success: false, Message: "Record is not in PENDING_APPROVAL status", ReturnCode: "INVALID_STATUS"}, nil
	}

	// 4-Eyes Principle constraint: Maker != Checker
	checkerID := req.GetCheckerId()
	if checkerID == "" {
		checkerID = shared.GetUsernameFromCtx(ctx)
	}

	if record.MakerID != "" && checkerID != "" && record.MakerID == checkerID {
		return &fndv1.SaveResponse{Success: false, Message: "4-Eyes Principle Violation: Maker cannot be the Checker", ReturnCode: "FOUR_EYES_VIOLATION"}, nil
	}

	// Process Approval/Rejection
	if req.GetIsApproved() {
		record.Status = models.StatusApproved
	} else {
		record.Status = models.StatusRejected
	}
	
	record.CheckerID = &checkerID
		remark := req.GetRemark()
	record.Remark = &remark

	if err := s.db.WithContext(ctx).Save(&record).Error; err != nil {
		s.log.Error("Failed to update status", slog.Any("error", err))
		return &fndv1.SaveResponse{Success: false, Message: "Failed to update record", ReturnCode: "DB_ERROR"}, nil
	}

	return &fndv1.SaveResponse{Success: true, Message: "Record reviewed successfully", ReturnCode: "0000"}, nil
}
